# Site settings
description: "Kun Liu's personal website"

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title.html

# Pagination
paginate: 5
paginate_path: "blog/page/:num"
