version: 2.0

jobs:
    build:
        docker:
            - image: felicianotech/docker-hugo:latest
        working_directory: ~/kwunlyou.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "5d:7a:fb:32:45:83:1e:08:55:3e:11:94:f6:2f:b4:ce"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: git clone -b master git@github.com:kwunlyou/kwunlyou.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/kwunlyou.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "zju.liukun@gmail.com"
                    git config user.name "kwunlyou"
                    git add .
                    git commit --allow-empty -m "new deployment"
                    git push -q git@github.com:kwunlyou/kwunlyou.github.io.git master

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: dev